# Generated by Django 5.1.6 on 2025-03-19 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_restocklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restocklog',
            name='added_by',
        ),
        migrations.AddField(
            model_name='restocklog',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.supplier'),
        ),
    ]
